#!/bin/sh
# Monte systeme fichier virtuel qui gere les processus
mount proc /proc -t proc
# Monte en lecture ecriture le système de fichier racine
mount / -o remount,rw


# Load la key map en fr
loadkmap < /etc/french.kmap


# Network config
/etc/init.d/rc.network &

login
